version: "3.7"
services:
  db:
    image: postgres:12
    container_name: chirp-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=chirp_dev
      - DATABASE_HOST=localhost
    volumes:
      - ./mysql/sqls:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
